### ISSUE TITLE
extension doesn't see apio when it is installed

### ISSUE THREAD

**Issue by Ethycs** [r1cebank/icestorm-vscode-extension#4]
Hi,

I've installed apio on my standard python environment. It's not being picked up by the extension.

**Comment by r1cebank** [comment]
Are you using virtualenv?

**Comment by Ethycs** [comment]
I'm using miniconda and I have a powershell profile setup to switch to the environment. Some kind of switch likely needs to be exposed in the .json settings to switch to the right context 👍

**Comment by Ethycs** [comment]
![Screenshot 2021-02-21 102034](https://user-images.githubusercontent.com/11140224/108634461-83979880-742e-11eb-98f2-542482d90e7f.png)
 
This is from my Vscode terminal, so obviously I can access apio, but the extension doesn't see the env

**Comment by r1cebank** [comment]
You are on windows correct? The extension uses the default path for launching commands so it might not see your PATH. I might need to rebuild this a bit. Can you try to launch vscode from the terminal that have the profile switched and see if you can access apio?

**Comment by Ethycs** [comment]
![image](https://user-images.githubusercontent.com/11140224/108636620-4be31d80-743b-11eb-8205-a79510245d1c.png)
Running vscode from the shell that has my python env works.

I am on Windows

**Comment by r1cebank** [comment]
Good to hear, I’ll see how I can make the plug-in work with this type of configuration.

**Comment by r1cebank** [comment]
An option for overriding the tool path has been added to 1.0.6. https://github.com/r1cebank/icestorm-vscode-extension#path-overrides
